# Generated by Django 4.1.5 on 2023-07-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_productgallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urunler',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
