# Generated by Django 4.2 on 2023-05-11 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kart_id', models.CharField(blank=True, max_length=250)),
                ('Tarih_ekle', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='KartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Miktar', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('kart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kartlar.kart')),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.urunler')),
            ],
        ),
    ]
