# Generated by Django 4.2 on 2023-07-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_variation'),
        ('kartlar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kartitem',
            name='variations',
            field=models.ManyToManyField(blank=True, to='store.variation'),
        ),
    ]
